name: 01 - Deploy infrastructure

on:
  workflow_dispatch:
    inputs: {}

env:
  resource_group: acilab
  location: westeurope
  public_domain: "cloudtrooper.net"
  private_domain: "cloudtrooper.net"

jobs:
  create_infra:
    runs-on: ubuntu-latest
    steps:

      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@v2

      # log into Azure
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run script in repo
      - name: "Deploy infrastructure"
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/scripts/init_rg.sh
            $GITHUB_WORKSPACE/scripts/init_rg.sh \
                -g=${{ env.resource_group }} \
                -l=${{ env.location }} \
                -u=${{ secrets.SQL_USERNAME }} \
                -p=${{ secrets.SQL_PASSWORD }} \
                -z=${{ env.private_domain }} \
                -d=${{ env.public_domain }}

