name: 01 - Deploy infrastructure

on:
  workflow_dispatch:
    inputs: {}

env:
  resource_group: acilab
  location: westeurope
  public_domain: "cloudtrooper.net"
  private_domain: "cloudtrooper.net"

jobs:
  create_infra:
    runs-on: ubuntu-latest
    steps:

      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      # log into Azure
      - name: "Login via Azure CLI"
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Run script in repo
      - name: "Deploy infrastructure"
        uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/scripts/init_rg.sh
            $GITHUB_WORKSPACE/scripts/init_rg.sh \
                -g=${{ env.resource_group }} \
                -l=${{ env.location }} \
                -u=${{ secrets.SQL_USERNAME }} \
                -p=${{ secrets.SQL_PASSWORD }} \
                -z=${{ env.private_domain }} \
                -d=${{ env.public_domain }}

