name: 02 - Build images

on:
  workflow_dispatch:
    inputs: {}

env:
  resource_group: acilab
  repo_name: acilab

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      # log into Azure
      - name: "Login via Azure CLI"
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      # Run script in repo
      - name: Build images to ACR
        uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/scripts/build_images.sh
            $GITHUB_WORKSPACE/scripts/build_images.sh \
                -g=${{ env.resource_group }} \
                -r=${{ env.repo_name }} \
                -d=$GITHUB_WORKSPACE
