name: 05 - Configure App Gateway

on:
  workflow_dispatch:
    inputs: {}

env:
  resource_group: acilab
  public_domain: "cloudtrooper.net"
  private_domain: "cloudtrooper.net"

jobs:
  config_appgw:
    runs-on: ubuntu-latest
    steps:
      # checkout branch
      - name: git checkout main branch
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      # log into Azure
      - name: "Login via Azure CLI"
        uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      # Run script in repo
      - name: "Configure App GW rules"
        uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/scripts/config_appgw.sh
            $GITHUB_WORKSPACE/scripts/config_appgw.sh \
                -g=${{ env.resource_group }} \
                -z=${{ env.private_domain }} \
                -d=${{ env.public_domain }}
